package graptorq

import (
	"bytes"
	"encoding/hex"
	"testing"

	"github.com/mholland/graptorq/internal/testutil"
)

// Golden vectors generated by cberner/raptorq 2.0.1 (tools/rqoracle
// gen-vectors). Encoding symbols must match byte for byte, including source
// block partitioning and sub-block interleaving; decode vectors must decode;
// and the Section 4.3 parameter derivation must agree.
func TestCbernerVectors(t *testing.T) {
	vectors, err := testutil.LoadOracleVectors("testdata/vectors/cberner-2.0.1/vectors.jsonl.gz")
	if err != nil {
		t.Fatal(err)
	}
	var objects, symbols, derives int
	for _, v := range vectors {
		otiBytes, _ := hex.DecodeString(v.OTI)
		oti, err := ParseOTI(otiBytes)
		if err != nil {
			t.Fatalf("%s: cberner OTI %s rejected: %v", v.Name, v.OTI, err)
		}
		if b, _ := oti.MarshalBinary(); !bytes.Equal(b, otiBytes) {
			t.Fatalf("%s: OTI re-encodes as %x", v.Name, b)
		}

		if v.Name == "derive" {
			derives++
			T := v.MTU - v.MTU%8
			got, err := DeriveOTI(v.F, Config{PayloadSize: T, Alignment: 8, MinSubSymbolSize: 8, WorkingMemory: 10 << 20})
			if err != nil || got != oti {
				t.Errorf("DeriveOTI(F=%d, T=%d) = %+v, %v; cberner %+v", v.F, T, got, err, oti)
			}
			continue
		}

		objects++
		if testing.Short() && oti.TransferLength > 100_000 {
			continue
		}
		data := testutil.PatternData(int(oti.TransferLength), v.Seed)
		if v.Decode {
			dec, err := NewDecoder(oti)
			if err != nil {
				t.Fatal(err)
			}
			for _, s := range v.Symbols {
				b, _ := hex.DecodeString(s.Data)
				if _, err := dec.AddSymbol(PayloadID{s.SBN, s.ESI}, b); err != nil {
					t.Fatalf("%s: %v", v.Name, err)
				}
			}
			got, err := dec.AppendObject(nil)
			if err != nil || !bytes.Equal(got, data) {
				t.Errorf("%s %+v: failed to decode cberner packets (%v)", v.Name, oti, err)
			}
			continue
		}
		enc, err := NewEncoder(data, oti)
		if err != nil {
			t.Fatal(err)
		}
		for _, s := range v.Symbols {
			got, err := enc.AppendSymbol(nil, PayloadID{s.SBN, s.ESI})
			if err != nil {
				t.Fatalf("%s: %v", v.Name, err)
			}
			symbols++
			if hex.EncodeToString(got) != s.Data {
				t.Errorf("%s %+v SBN=%d ESI=%d:\n got %x\nwant %s", v.Name, oti, s.SBN, s.ESI, got, s.Data)
			}
		}
	}
	t.Logf("%d objects (%d encoding symbols compared), %d derivations", objects, symbols, derives)
}
