// Package testutil holds test vectors and helpers shared by the tests of
// several packages. It is not used by non-test code.
package testutil

// SymbolVector is a known encoding symbol of a single source block.
type SymbolVector struct {
	ESI uint32 // encoding symbol ID (may exceed 2^24-1 for the xssnick vector)
	Hex string
}

// BlockVector is a source block together with known encoding symbols.
type BlockVector struct {
	Name       string
	Data       []byte
	SymbolSize int
	Symbols    []SymbolVector
}

// VectorData returns the deterministic data pattern data[i] = i*31 + 7 used by
// the cberner-generated vectors.
func VectorData(n int) []byte {
	d := make([]byte, n)
	for i := range d {
		d[i] = byte(uint32(i)*31 + 7)
	}
	return d
}

// BlockVectors returns known-answer vectors for single-block encoding.
//
// Sources:
//   - "xssnick": the only known-answer test of github.com/xssnick/raptorq
//     v1.5.2 (Test_Encode). Its ESI exceeds the 24-bit wire limit, so it can
//     only be checked with an internal-ISI hook.
//   - all others: repair symbols generated by cberner/raptorq 2.0.1 and
//     published in github.com/takeyourhatoff/raptorq (MIT License,
//     solver_test.go).
func BlockVectors() []BlockVector {
	hello := []byte("hello world bro! keke meme 881")
	vs := []BlockVector{
		{
			Name: "xssnick", Data: hello, SymbolSize: 20,
			Symbols: []SymbolVector{{68238283, "05e6ddeb1f820e0a0f318b23128d889623663e66"}},
		},
		{
			Name: "hello", Data: hello, SymbolSize: 20,
			Symbols: []SymbolVector{
				{2, "fad495fe96b2c6637eec642062726f21206b656b"},
				{3, "404dd4539e4b8678ccc1a698327eca5598d96bd9"},
				{10000, "98ccb370fd733f2db552dd1341c65e2913b6e7b6"},
			},
		},
		{
			Name: "sequence", Data: VectorData(100), SymbolSize: 16,
			Symbols: []SymbolVector{
				{7, "6351b8e43abf14791de18013f10d6cff"},
				{8, "734740d6742d14662e8ed471b1114bee"},
				{1000, "2d5108c60c24ea1bd86c2675f5410b58"},
				{1<<24 - 1, "62e5468efb3b63de9a26dd619d21da66"},
			},
		},
	}
	for _, c := range []struct {
		k    uint32
		want [3]string
	}{
		{10, [3]string{"b1fdcff70945774f", "d0db63e2d3d860e1", "da93f8ba90d9b2f0"}},
		{11, [3]string{"f0a8e453722a66d1", "874aac909b56b08c", "8f51a4a321ff0a0d"}},
		{49, [3]string{"d781bc28d680bd29", "06b6c28db606723d", "17f48eeaf013690d"}},
		{50, [3]string{"fc2d024913c2eda6", "698f611e688e601f", "2c3fcd8facbf4d0f"}},
		{1021, [3]string{"8f9f31f4f4e44a8f", "5fd59ad80983cc8e", "47bd63beae548a57"}},
		{4096, [3]string{"cc7d40a2eb5a6785", "48f0e72cb20a1dd6", "c86128bf49e0a93e"}},
	} {
		v := BlockVector{Name: "transition", Data: VectorData(int(c.k) * 8), SymbolSize: 8}
		for i, off := range []uint32{0, 17, 1000} {
			v.Symbols = append(v.Symbols, SymbolVector{c.k + off, c.want[i]})
		}
		vs = append(vs, v)
	}
	return vs
}

// TransitionRepairs are 8 repair symbols (ESIs 50..57) generated by
// cberner/raptorq 2.0.1 for VectorData(400) with symbol size 8 (K=50).
var TransitionRepairs = []string{
	"fc2d024913c2eda6", "f607ebe08b7a969d", "1ba7bc7ca61a01c1", "c3fa34242c15dbcb",
	"52648099c2f41009", "215320838efc8f2c", "b2b906e0b8b30cea", "ac7fc73e9b48f009",
}
