// Command gentables generates internal/rfc/tables_gen.go from the text of
// RFC 6330 so that no table is transcribed by hand.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"

	"github.com/mstephenholl/graptor-q/internal/rfc/rfctext"
)

func main() {
	in := flag.String("in", "../../testdata/rfc6330.txt", "path to rfc6330.txt")
	out := flag.String("out", "tables_gen.go", "output Go file")
	flag.Parse()

	text, err := os.ReadFile(*in)
	if err != nil {
		log.Fatal(err)
	}
	t, err := rfctext.Parse(text)
	if err != nil {
		log.Fatal(err)
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by internal/rfc/gentables from testdata/rfc6330.txt; DO NOT EDIT.\n\n")
	b.WriteString("package rfc\n\n")
	for i, v := range t.V {
		fmt.Fprintf(&b, "// v%d is the table V%d of RFC 6330 Section 5.5.%d.\nvar v%d = [256]uint32{", i, i, i+1, i)
		for j, x := range v {
			if j%8 == 0 {
				b.WriteString("\n")
			}
			fmt.Fprintf(&b, "%d, ", x)
		}
		b.WriteString("\n}\n\n")
	}

	b.WriteString("// degF is Table 1 of RFC 6330 Section 5.3.5.2 (f[0..30]).\nvar degF = [31]uint32{")
	for j, x := range t.DegF {
		if j%8 == 0 {
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "%d, ", x)
	}
	b.WriteString("\n}\n\n")

	fmt.Fprintf(&b, "// systematic is Table 2 of RFC 6330 Section 5.6: K', J(K'), S(K'), H(K'), W(K').\n")
	fmt.Fprintf(&b, "var systematic = [%d]tableRow{\n", len(t.Systematic))
	for _, r := range t.Systematic {
		fmt.Fprintf(&b, "{%d, %d, %d, %d, %d},\n", r.KPrime, r.J, r.S, r.H, r.W)
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}
