package gf256

import (
	"bytes"
	"fmt"
	"math/rand/v2"
	"os"
	"testing"

	"github.com/mholland/graptorq/internal/rfc/rfctext"
)

func rfcTables(t testing.TB) *rfctext.Tables {
	t.Helper()
	text, err := os.ReadFile("../../testdata/rfc6330.txt")
	if err != nil {
		t.Fatal(err)
	}
	tables, err := rfctext.Parse(text)
	if err != nil {
		t.Fatal(err)
	}
	return tables
}

// The field is built from the polynomial; the RFC defines it by tables. Check
// every product, quotient and inverse against the RFC formulas (Section 5.7.2).
func TestFieldMatchesRFC(t *testing.T) {
	rt := rfcTables(t)
	if rt.OctExp != expTable {
		t.Fatal("OCT_EXP differs from the table generated by polynomial 0x11D")
	}
	for a := 1; a < 256; a++ {
		if rt.OctLog[a] != logTable[a] {
			t.Fatalf("OCT_LOG[%d] = %d, got %d", a, rt.OctLog[a], logTable[a])
		}
	}
	for a := range 256 {
		for b := range 256 {
			want := byte(0)
			if a != 0 && b != 0 {
				want = rt.OctExp[int(rt.OctLog[a])+int(rt.OctLog[b])]
			}
			if got := Mul(byte(a), byte(b)); got != want {
				t.Fatalf("Mul(%d,%d) = %d, want %d", a, b, got, want)
			}
			if b != 0 {
				want = 0
				if a != 0 {
					want = rt.OctExp[int(rt.OctLog[a])-int(rt.OctLog[b])+255]
				}
				if got := Div(byte(a), byte(b)); got != want {
					t.Fatalf("Div(%d,%d) = %d, want %d", a, b, got, want)
				}
			}
		}
		if a != 0 {
			if got, want := Inv(byte(a)), rt.OctExp[255-int(rt.OctLog[a])]; got != want {
				t.Fatalf("Inv(%d) = %d, want %d", a, got, want)
			}
			if Mul(byte(a), Inv(byte(a))) != 1 {
				t.Fatalf("a * Inv(a) != 1 for a=%d", a)
			}
		}
	}
	for i := range 1000 {
		if got, want := Exp(i), rt.OctExp[i%255]; got != want {
			t.Fatalf("Exp(%d) = %d, want %d", i, got, want)
		}
	}
}

func TestDistributive(t *testing.T) {
	for a := range 256 {
		ta := &mulTable[a]
		for b := range 256 {
			for c := range 256 {
				if ta[b^c] != ta[b]^ta[c] {
					t.Fatalf("a*(b+c) != a*b + a*c for %d,%d,%d", a, b, c)
				}
			}
		}
	}
}

// affine emulates GF2P8AFFINEQB for one byte with a zero constant.
func affine(x byte, a uint64) byte {
	var out byte
	for i := range 8 {
		row := byte(a >> (8 * (7 - i)))
		var parity byte
		for v := row & x; v != 0; v &= v - 1 {
			parity ^= 1
		}
		out |= parity << i
	}
	return out
}

func TestAffineMatrix(t *testing.T) {
	if gfniMatrix[1] != 0x0102040810204080 {
		t.Fatalf("identity matrix = %#x", gfniMatrix[1])
	}
	for c := range 256 {
		for x := range 256 {
			if got, want := affine(byte(x), gfniMatrix[c]), Mul(byte(c), byte(x)); got != want {
				t.Fatalf("affine(%d, M[%d]) = %d, want %d", x, c, got, want)
			}
		}
	}
}

func TestNibbleTables(t *testing.T) {
	for c := range 256 {
		for x := range 256 {
			got := nibbleTables[c][x&15] ^ nibbleTables[c][16+x>>4]
			if want := Mul(byte(c), byte(x)); got != want {
				t.Fatalf("nibble(%d,%d) = %d, want %d", c, x, got, want)
			}
		}
	}
}

// forEachTier runs f once with every supported kernel tier active.
func forEachTier(t *testing.T, f func(t *testing.T)) {
	for _, name := range Tiers() {
		t.Run(name, func(t *testing.T) {
			defer Use(name)()
			f(t)
		})
	}
}

func refMulAdd(dst, src []byte, c byte) {
	for i := range src {
		dst[i] ^= Mul(c, src[i])
	}
}

var testLengths = func() []int {
	var n []int
	for i := 0; i <= 260; i++ {
		n = append(n, i)
	}
	return append(n, 511, 512, 513, 1023, 1280, 4096+13, 65536+7)
}()

func TestKernels(t *testing.T) {
	forEachTier(t, func(t *testing.T) {
		rng := rand.New(rand.NewPCG(1, 2))
		buf := make([]byte, 3*(65536+64))
		for _, n := range testLengths {
			for _, c := range []byte{0, 1, 2, 3, 0x1d, 0x80, 0xfe, 0xff, byte(rng.IntN(256))} {
				off := rng.IntN(32)
				for i := range buf {
					buf[i] = byte(rng.Uint32())
				}
				src := buf[off : off+n]
				dst := buf[len(buf)/2+off/2 : len(buf)/2+off/2+n]
				orig := bytes.Clone(dst)

				want := bytes.Clone(orig)
				refMulAdd(want, src, c)
				MulAddSlice(dst, src, c)
				if !bytes.Equal(dst, want) {
					t.Fatalf("MulAddSlice n=%d c=%d off=%d mismatch", n, c, off)
				}

				copy(dst, orig)
				want = make([]byte, n)
				refMulAdd(want, src, c)
				MulSlice(dst, src, c)
				if !bytes.Equal(dst, want) {
					t.Fatalf("MulSlice n=%d c=%d off=%d mismatch", n, c, off)
				}

				copy(dst, orig)
				want = bytes.Clone(orig)
				refMulAdd(want, src, 1)
				AddSlice(dst, src)
				if !bytes.Equal(dst, want) {
					t.Fatalf("AddSlice n=%d off=%d mismatch", n, off)
				}

				// In place: dst = c*dst, and dst = c*dst ^ src.
				copy(dst, orig)
				want = make([]byte, n)
				refMulAdd(want, orig, c)
				MulSlice(dst, dst, c)
				if !bytes.Equal(dst, want) {
					t.Fatalf("in-place MulSlice n=%d c=%d mismatch", n, c)
				}
				copy(dst, orig)
				refMulAdd(want, src, 1)
				ScaleAdd(dst, src, c)
				if !bytes.Equal(dst, want) {
					t.Fatalf("ScaleAdd n=%d c=%d mismatch", n, c)
				}
			}
		}
	})
}

func TestAllConstants(t *testing.T) {
	forEachTier(t, func(t *testing.T) {
		src := make([]byte, 256+77)
		for i := range src {
			src[i] = byte(i)
		}
		for c := range 256 {
			dst := make([]byte, len(src))
			MulSlice(dst, src, byte(c))
			for i, s := range src {
				if dst[i] != Mul(byte(c), s) {
					t.Fatalf("MulSlice c=%d x=%d", c, s)
				}
			}
			MulAddSlice(dst, src, byte(c))
			for i := range dst {
				if dst[i] != 0 {
					t.Fatalf("MulAddSlice c=%d did not cancel at %d", c, i)
				}
			}
		}
	})
}

func TestFusedXor(t *testing.T) {
	forEachTier(t, func(t *testing.T) {
		rng := rand.New(rand.NewPCG(15, 16))
		for _, n := range append(testLengths[:70:70], 95, 96, 97, 127, 128, 129, 1280, 4096+13) {
			for _, k := range []int{0, 1, 2, 3, 7, 8, 9, 16, 17} {
				srcs := make([][]byte, k)
				for i := range srcs {
					srcs[i] = make([]byte, n+rng.IntN(3))[:n] // unaligned capacity
					for j := range srcs[i] {
						srcs[i][j] = byte(rng.Uint32())
					}
				}
				orig := make([]byte, n)
				for j := range orig {
					orig[j] = byte(rng.Uint32())
				}
				want := make([]byte, n)
				for _, s := range srcs {
					refMulAdd(want, s, 1)
				}
				dst := bytes.Clone(orig)
				SetXor(dst, srcs)
				if !bytes.Equal(dst, want) {
					t.Fatalf("SetXor n=%d k=%d mismatch", n, k)
				}
				refMulAdd(want, orig, 1)
				dst = bytes.Clone(orig)
				XorN(dst, srcs)
				if !bytes.Equal(dst, want) {
					t.Fatalf("XorN n=%d k=%d mismatch", n, k)
				}
			}
		}
	})
}

func TestFusedXorNoAlloc(t *testing.T) {
	forEachTier(t, func(t *testing.T) {
		dst := make([]byte, 1000)
		srcs := [][]byte{make([]byte, 1000), make([]byte, 1000), make([]byte, 1000)}
		if n := testing.AllocsPerRun(100, func() { SetXor(dst, srcs) }); n != 0 {
			t.Errorf("SetXor allocates %.0f times", n)
		}
	})
}

func TestHDPCStep(t *testing.T) {
	forEachTier(t, func(t *testing.T) {
		rng := rand.New(rand.NewPCG(17, 18))
		random := func(n int) []byte {
			b := make([]byte, n)
			for i := range b {
				b[i] = byte(rng.Uint32())
			}
			return b
		}
		for _, n := range testLengths {
			for _, alias := range []bool{false, true} {
				z, y, h1, h2 := random(n), random(n), random(n), random(n)
				if alias {
					h2 = h1
				}
				wz, wh1, wh2 := make([]byte, n), bytes.Clone(h1), bytes.Clone(h2)
				for i := range n {
					wz[i] = Mul(2, z[i]) ^ y[i]
				}
				refMulAdd(wh1, wz, 1)
				if alias {
					wh2 = wh1
					refMulAdd(wh2, wz, 1)
				} else {
					refMulAdd(wh2, wz, 1)
				}
				HDPCStep(z, y, h1, h2)
				if !bytes.Equal(z, wz) || !bytes.Equal(h1, wh1) || !bytes.Equal(h2, wh2) {
					t.Fatalf("n=%d alias=%v: mismatch", n, alias)
				}
			}
		}
	})
}

func TestXorGather(t *testing.T) {
	forEachTier(t, func(t *testing.T) {
		rng := rand.New(rand.NewPCG(19, 20))
		for _, n := range []int{1, 7, 31, 32, 33, 64, 95, 96, 100, 1280, 1283} {
			stride := n + rng.IntN(64)
			base := make([]byte, 40*stride)
			for i := range base {
				base[i] = byte(rng.Uint32())
			}
			for _, k := range []int{0, 1, 2, 7, 8, 9, 16, 17} {
				for _, withFirst := range []bool{false, true} {
					for _, acc := range []bool{false, true} {
						idx := make([]uint16, k)
						for i := range idx {
							idx[i] = uint16(rng.IntN(40))
						}
						var first []byte
						if withFirst {
							first = make([]byte, n)
							for i := range first {
								first[i] = byte(rng.Uint32())
							}
						}
						orig := make([]byte, n)
						for i := range orig {
							orig[i] = byte(rng.Uint32())
						}
						want := make([]byte, n)
						if acc {
							copy(want, orig)
						}
						if first != nil {
							refMulAdd(want, first, 1)
						}
						for _, i := range idx {
							refMulAdd(want, base[int(i)*stride:int(i)*stride+n], 1)
						}
						dst := bytes.Clone(orig)
						XorGather(dst, first, base, stride, idx, acc)
						if !bytes.Equal(dst, want) {
							t.Fatalf("n=%d k=%d first=%v acc=%v: mismatch", n, k, withFirst, acc)
						}
					}
				}
			}
		}
	})
}

func TestLengthMismatchPanics(t *testing.T) {
	defer func() {
		if recover() == nil {
			t.Fatal("no panic")
		}
	}()
	AddSlice(make([]byte, 3), make([]byte, 4))
}

func FuzzMulAdd(f *testing.F) {
	f.Add([]byte("hello, world: a symbol of some length"), byte(7), uint8(3))
	f.Fuzz(func(t *testing.T, data []byte, c byte, off uint8) {
		o := int(off) % (len(data) + 1)
		src := data[o:]
		want := make([]byte, len(src))
		refMulAdd(want, src, c)
		for _, name := range Tiers() {
			restore := Use(name)
			dst := make([]byte, len(src))
			MulAddSlice(dst, src, c)
			restore()
			if !bytes.Equal(dst, want) {
				t.Fatalf("tier %s: mismatch", name)
			}
		}
	})
}

func BenchmarkKernels(b *testing.B) {
	for _, name := range Tiers() {
		for _, n := range []int{64, 1280, 16384} {
			src := make([]byte, n)
			dst := make([]byte, n)
			for i := range src {
				src[i] = byte(i * 7)
			}
			run := func(op string, f func()) {
				b.Run(fmt.Sprintf("tier=%s/op=%s/n=%d", name, op, n), func(b *testing.B) {
					defer Use(name)()
					b.SetBytes(int64(n))
					for b.Loop() {
						f()
					}
				})
			}
			run("xor", func() { AddSlice(dst, src) })
			run("mul", func() { MulSlice(dst, src, 0x53) })
			run("muladd", func() { MulAddSlice(dst, src, 0x53) })
			srcs := [][]byte{src, src, src, src}
			b.Run(fmt.Sprintf("tier=%s/op=setxor4/n=%d", name, n), func(b *testing.B) {
				defer Use(name)()
				b.SetBytes(int64(5 * n))
				for b.Loop() {
					SetXor(dst, srcs)
				}
			})
		}
	}
}
